name: Format
on: [push]
jobs:
  ruff:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup UV
        uses: ./.github/actions/setup-uv

      - name: Install ruff
        run: uv add ruff
      - name: Run ruff
        run: uv run ruff check 

